src/commands/generate.plopfile.ts

Closes https://github.com/grafana/create-plugin/issues/38
* It validates the name and organization ID are entered
* It creates a new folder based on the name and organization id instead of creating the plugin in the current folder.

Improves create command user experience

---

.github/workflows/create-release.yml

GH releases aren't working because it references a nonexistent secret. This PR fixes that.

CI: Use correct name for github-token when creating release

---

package.json
templates/common/.config/README.md
templates/common/.config/webpack/constants.ts
templates/common/.config/webpack/utils.ts
templates/common/.config/webpack/webpack.config.ts
templates/common/package.json
yarn.lock

This PR will add support for building nested plugins to the generated webpack configuration.
I have changed the exported webpack config to return a `Promise<Configuration>` instead of a `Configuration`. Will this cause any issues for plugins overriding the configuration?
Fixes #33

Build: Support for building nested plugins

---

templates/common/.config/webpack/utils.ts

When I introduced #50 I broke the support for single plugin repositories by always put the plugin `dist/${pluginName}/module.js`. This PR will fix that issue by always putting a single plugin repo directly below `dist/module.js`.
We should probably add tests for the most simple scenarios. Will open another PR about that.

Bugfix: building a single plugin as module directly in the dist folder

---

templates/common/package.json

This PR moves `@types/lodash` to devDependencies and adds `react` and `react-dom` to dependencies to remove unmet peer dependency warnings.
Fixes: #63

Templates: move @types/lodash and add react and react-dom to dependencies

---

templates/common/.config/webpack/webpack.config.ts

Adding this fix for app plugins that bundling as per this recent [toolkit change](https://github.com/grafana/grafana/pull/54519/files#diff-ab8cd65444c9468f00e7a77245af7724728e3f24105761c449531f9eee1a6090)

Templates: Externalise react-router to prevent bundling with plugins

---

src/commands/migrate.command.ts
src/utils/utils.npm.ts

This PR adds a clean up function to make sure the package.json is in a state that package managers would expect (alphabetised dependencies and devDependencies) and scripts are sorted to make it easier for a developer to scan.
| Before | After |
| --- | --- |
| <img width="978" alt="Screenshot 2022-10-06 at 12 11 08" src="https://user-images.githubusercontent.com/73201/194287510-ea573ebb-4aa5-4a38-b416-7d662b303ec5.png"> | <img width="979" alt="Screenshot 2022-10-06 at 12 09 49" src="https://user-images.githubusercontent.com/73201/194287521-4d2ac23e-4429-460a-88ac-8fee06208cae.png"> |
Fixes: #48

Migrate: Sort package.json fields

---

README.md

Closes https://github.com/grafana/create-plugin/issues/53
Removes extended description on how to create and run a plugin. This content should be later part of the main documentation.

Updates README about creating a new plugin

---

templates/common/jest.config.js

Snapshots and tests that use Date() will fail when generated locally in different timezones.  This forces jest to use UTC so the results will be reliable.
fixes #60

Templates: Set timezone to UTC for jest

---

templates/github/ci/.github/workflows/release.yml

Moving the release workflow to use plugincheck2 and the publishing config.
Fixes: #43

Templates: Use plugincheck2 in release workflow

---

packages/create-plugin/templates/common/.config/README.md
packages/create-plugin/templates/common/.config/tsconfig.json
packages/create-plugin/templates/common/.config/webpack/tsconfig.webpack.json
packages/create-plugin/templates/common/package.json

Fixes https://github.com/grafana/create-plugin/issues/71
Instead of using an environment variable it uses an overwrite in the tsconfig for ts-node (which transpiles the webpack config).
the transpiler `ts-node/transpilers/swc-experimental` was removed from the config as it was creating problems with ts-node and it is a minimal optimization in speed for this specific case.
With these changes the generated scripts run natively in windows.

Do not use TS_NODE_PROJECT for webpack configuration

---

packages/create-plugin/templates/github/ci/.github/workflows/ci.yml

Fixes https://github.com/grafana/plugin-tools/issues/41
We generate the e2e script by default with valid e2e tests by default. We can add the e2e step into the workflow

Add e2e to CI workflow

---

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

Fixes https://github.com/grafana/plugin-tools/issues/54
Adds a condition for webpack to not clean built binaries

Prevent webpack to clean binaries from go

---

.github/ISSUE_TEMPLATE/bug_report.yml

The bug_report.yml [isn't working](https://github.com/grafana/plugin-tools/issues/new/choose). I believe it's due to a missing description key which according to the [docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#top-level-syntax) is required.
Fixes #

Chore: Add missing required "description" key to issue_templates

---

packages/create-plugin/src/commands/update.command.ts
packages/create-plugin/src/constants.ts

Closes https://github.com/grafana/plugin-tools/issues/80
Create-plugin overwrites all the `.config` folder when `update` runs. This PR changes the prompt to confirm the update that was previously suggestion a list of files was to be displayed

Change update prompt message to clarify what is updating

---

packages/create-plugin/templates/common/.config/jest.config.js
packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

Toolkit's webpack config adds `src` to the list of module lookups allowing devs to write paths in a similar fashion to typescript `rootDir` feature. This PR adds this to webpack and jest.
Fixes #101

Fix: Make sure webpack and jest can resolve "rootDir" paths

---

packages/create-plugin/scripts/generate-app.js

Adjusts the script that is run when calling `yarn generate-app` to **not** include the backend by default. I think this case needs a bit more love.

App: disable backend by default in yarn generate-app

---

packages/create-plugin/src/constants.ts

Closes https://github.com/grafana/plugin-tools/issues/102
This PR extends the post-migration success message to better inform the user on custom configurations and what to do next.

Update post-migration message

---

packages/create-plugin/templates/common/.config/jest.config.js

The package @grafana/data 9.2.1, includes the "open layers" `ol` library. This fails to be imported by jest:
```
Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
By default "node_modules" folder is ignored by transformers.
Here's what you can do:
...
Details:
<plugin_path>/node_modules/ol/format/WKT.js:19
import Feature from '../Feature.js';
^^^^^^
SyntaxError: Cannot use import statement outside a module
at Runtime.createScriptFromCode …
```

Jest: Ignore ol library

---

packages/create-plugin/src/utils/utils.handlebars.ts
packages/create-plugin/templates/common/docker-compose.yaml

Fixes: https://github.com/grafana/plugin-tools/issues/62
Using the pluginId instead of only the pluginName
Example of a newly generated docker-compose file:
```yml
version: '3.0'
services:
grafana:
container_name: 'myorg-myplugin-panel'
build:
context: ./.config
args:
grafana_version: ${GRAFANA_VERSION:-9.1.2}
ports:
- 3000:3000/tcp
volumes:
- ./dist:/var/lib/grafana/plugins/myorg-myplugin-panel
- ./provisioning:/etc/grafana/provisioning
```

Use normalize_id for docker-compose.yml instead of only pluginName

---

packages/create-plugin/templates/common/.config/jest.config.js

Closes https://github.com/grafana/plugin-tools/issues/111
This is an initial solution to the problem described in https://github.com/grafana/plugin-tools/issues/111
It is not feaseable for now to create an maintain a list of packages that need transformation and we'll investigate later in the future a better performant solution.
For now, even though slower, this guarantees tests to run inside jest with ESM and commonjs code.

Instruct jest to transform all packages (including all inside node_modules)

---

.github/workflows/test.yml
packages/sign-plugin/src/bin/run.ts
packages/sign-plugin/src/commands/sign.command.ts
packages/sign-plugin/src/utils/getVersion.ts
packages/sign-plugin/src/utils/manifest.ts

This PR tries to clean up sign-plugin to get it in a state where we can cut a first release.
Fixes #

Sign-Plugin: Clean up, improve error messages, add basic CI steps

---

packages/create-plugin/src/commands/migrate.command.ts
packages/create-plugin/src/constants.ts
packages/create-plugin/src/utils/utils.npm.ts

This PR prevents create-plugin from updating any `@grafana/` dependencies that are already listed in a plugins `package.json` when running `npx @create-plugin migrate`. Doing so should ease the pain for a plugin developer migrating without needing to edit source code to deal with typescript errors in build or test.
This feels a little tricky to implement as we rely heavily on the templates for location of dependencies and delete `@grafana/**` dependencies that are listed as `devDependencies` when they should be `dependencies` etc. This led me to opt for to storing references to the "original" package versions then, when calculating the NPM updates, use these references instead to keep the moving / deleting logic without changing the package …

Create-Plugin: Ignore grafana dependencies when migrating

---

packages/create-plugin/templates/common/.config/jest.config.js
packages/create-plugin/templates/common/.config/mocks/react-inlinesvg.tsx

Removes a recurrent jest react error when testing components using grafana/ui components that display icons.
Fixes https://github.com/grafana/plugin-tools/issues/120

Add a manual mock for react-inlinesvg to prevent errors when running test with grafana-ui and icons

---

packages/sign-plugin/src/commands/sign.command.ts

The sign command code expects rootUrl to always be an array regardless of what is passed.
Fixes #130 
I'm gonna open a separate issue for writing some tests for sign-plugin package.
<details>
<br />
```bash
npm install @grafana/sign-plugin@0.0.2-canary.136.8403097.0
yarn add @grafana/sign-plugin@0.0.2-canary.136.8403097.0
```
</details>

Fix: Prevent error if rootUrls arg is not passed

---

packages/create-plugin/src/utils/tests/utils.handlebars.test.ts
packages/create-plugin/src/utils/utils.handlebars.ts

Users can type all sorts into the prompts when scaffolding a new plugin. Right now the `normalizeId` function strips uppercase characters which creates incorrect IDs (see path of directory created below):
```
success Installed "@grafana/create-plugin@0.5.0" with binaries:
- create-plugin
? What is going to be the name of your plugin? My Plugin
? What is the organization name of your plugin? HeyWesty
? How would you describe your plugin?
? What kind of plugin would you like?  panel
? Do you want to add Github CI and Release workflows? Yes
? Do you want to add a Github workflow for automatically checking "Grafana API compatibility" on PRs? Yes
✔  ++ /Users/jackwestbrook/Sandbox/plugin-tools-tests/eyesty-ylugin-panel/.config/.eslintrc
```
**Which …

Fix: include uppercase characters when normalising plugin id

---

packages/create-plugin/templates/backend/pkg/plugin/datasource.go

- Switched the log level in the backend template from `Info` to `Debug`
- Adds a comment to remind to not log sensitive information at `Info` level
Fixes #140

Create-Plugin: Backend template: Switch from Info to Debug level

---

packages/create-plugin/README.md

Makes it clear that we will not migrate any angular plugins.

Docs - make sure that angular is not supported

---

packages/create-plugin/src/commands/generate.plopfile.ts

Right now when we scaffold the different types of plugins in DEV we use the `force` property on plop actions so we can regenerate the plugin without needing to delete the plugin directory first. However for production cases we don't want to trash a developers plugin if they accidentally run the command.
This behaviour difference has a bug in production which prevents a pluginType or backend template (that should be used as an override) from being written to the same location. E.g If a user scaffolds a backend datasource there is `templates/datasource/src/datasource.ts` and `templates/backend/src/datasource.ts` and they should both be scaffolded to `src/datasource.ts`. Currently the first template found will be written and the second will fail …

Create Plugin: Fix incorrect templates being used for scaffolding

---

packages/create-plugin/src/commands/generate.plopfile.ts
packages/create-plugin/templates/datasource/src/plugin.json
packages/create-plugin/templates/panel/src/plugin.json

Generated links in plugin.json incorrectly point to the deprecated starter templates. This PR removes them.
Fixes #129
<details>
<br />
```bash
npm install @grafana/create-plugin@0.7.1-canary.162.e431ddf.0
yarn add @grafana/create-plugin@0.7.1-canary.162.e431ddf.0
```
</details>

Create Plugin: Remove links pointing to deprecated starter templates

---

packages/create-plugin/src/commands/generate.plopfile.ts
packages/create-plugin/templates/app/README.md
packages/create-plugin/templates/datasource/README.md
packages/create-plugin/templates/panel/README.md

Ensures instructions guide users towards building their plugin's backend before running docker.
Right now if you build a plugin with a backend with the create-plugin tool and follow the instructions as written you'll get a 503 error message with the message "plugin unavailable". This is because if you follow the instructions as currently written you are building the backend of your plugin (`mage -v`) _after_ you've run `yarn server` or `docker-compose up -build` which kicks of a dockerized version of grafana but which does not restart if the new files in your plugin are built. It may not be clear to the user that they need to restart yarn server/docker and/or run these commands in a different order.
I think in the future it would be awesome to add …

Create Plugin: Update docs to build backend before running docker

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/test-build.yml

Our release process needs to be able to push commits to main which is a protected branch. The automated GITHUB_TOKEN in workflows doesn't allow for this so going back to using a PAT. 😞

Revert "CI: Update workflows to use permissions rather than PAT"

---

packages/create-plugin/templates/common/.config/webpack/utils.ts
packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

Whilst debugging issues with migrating a plugin I discovered some developers nest plugins in directories deeper than one level. Builds were also breaking because it was accessing sass files in node_modules directory which was ignored. It's not the best of changes but I think is out of our control.
```
./dist
├── CHANGELOG.md
├── LICENSE
├── README.md
├── datasource
│   ├── module.js
│   ├── module.js.map
│   └── plugin.json
├── img
│   └── logo.svg
├── module.js
├── module.js.map
├── one
│   ├── module.js
│   └── module.js.map
├── panels
│   ├── one
│   │   └── plugin.json
│   └── two
│       └── with
│           └── a
│               └── nested
│                   └── path
│                       └── plugin.json
├── path
│   ├── module.js
│   └── …
```

Create Plugin: Fix deeply nested plugins

---

docusaurus/docs/advanced-configuration.md
packages/create-plugin/templates/common/.config/Dockerfile
packages/create-plugin/templates/common/.config/README.md

We got a question about why the `GF_ENTERPRISE_*` environment variables wasn't picked up properly after migrating to the `create-plugin` configuration files. The reason for this is that we are using the `grafana/grafana` docker image which doesn't contain the enerprise version of Grafana.
This PR will change so that all the docker related configuration that is scaffolded by `create-plugin` will use `grafana/grafana-enterprise` as the default docker image. It also adds a way to configure this without adding any changes to the `./config` folder which might cause issues while updating.
<details>
<br />
```bash
npm install …
```

CreatePlugin: Change default docker image to grafana-enterprise

---

packages/create-plugin/templates/backend/pkg/plugin/datasource.go

Following some recent plugin reviews, it appears that we have some work to do to encourage best practices for logging

Remove default logging examples as their usage is prone to user error

---

docusaurus/docs/creating-a-plugin.md
docusaurus/docs/getting-started.md
docusaurus/docs/migrating-from-toolkit.md
docusaurus/docs/nested-plugins.md
docusaurus/docs/updating-to-new-releases.md
packages/create-plugin/README.md
packages/create-plugin/templates/common/package.json
packages/sign-plugin/README.md

adding `@latest` to `npx` commands to avoid issues with local caching. Ref: https://github.com/npm/cli/issues/2329
grafana/grafana docs PR: https://github.com/grafana/grafana/pull/64140
<details>
<br />
```bash
npm install @grafana/create-plugin@1.0.1-canary.208.ba32fb6.0
npm install @grafana/sign-plugin@1.0.1-canary.208.ba32fb6.0
yarn add @grafana/create-plugin@1.0.1-canary.208.ba32fb6.0
yarn add @grafana/sign-plugin@1.0.1-canary.208.ba32fb6.0
```
</details>

Add `@latest` to docs and scripts using npx commands 

---

packages/create-plugin/templates/common/.config/webpack/utils.ts
packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

Keeps compiled binaries that don't follow the `gpx_.*` prefix in the `./dist` directory when webpack runs.
Fixes https://github.com/grafana/plugin-tools/issues/204
<details>
<br />
```bash
npm install @grafana/create-plugin@1.2.0-canary.207.948a872.0
npm install @grafana/sign-plugin@1.1.0-canary.207.948a872.0
yarn add @grafana/create-plugin@1.2.0-canary.207.948a872.0
yarn add @grafana/sign-plugin@1.1.0-canary.207.948a872.0
```
</details>

Keep custom executable name if defined

---

packages/create-plugin/templates/common/package.json

Similar to the changes in https://github.com/grafana/plugin-tools/pull/215, this PR removes the unnecessary dependencies in the generated plugins (dependencies which are either unused or [are defined as dependencies of the @grafana/eslint-config package](https://github.com/grafana/eslint-config-grafana/blob/master/package.json#L23)).
<details>
<br />
```bash
npm install @grafana/create-plugin@1.1.2-canary.221.156b869.0
yarn add @grafana/create-plugin@1.1.2-canary.221.156b869.0
```
</details>

Chore: Remove unused deps from scaffolded plugins

---

packages/create-plugin/templates/common/.config/README.md

The README.md copied to a plugin .config directory contains an incorrect path for extending jest configurations.
No issue opened
Minor doc update noticed while update plugins and needing to customize jest.  The docs on the main site are correct, this just syncs them up.

Documentation: Fix path in for template README.md for jest customizations

---

docusaurus/docs/advanced-configuration.md

Provides a more advanced example of extending the webpack configuration.
No issue right now.
I'm using this example config in a panel plugin to provide fallbacks to an external library.

create-plugin: documentation - add another webpack config example

---

packages/create-plugin/templates/common/package.json

Yarn 1's hoisting appears to cause `@types/react` version collisions resulting in failed app builds post scaffold due to react-router-dom bringing a different version with it. Removing them from the package.json seems to fix things.
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@1.3.1-canary.238.2a7fa4d.0
yarn add @grafana/create-plugin@1.3.1-canary.238.2a7fa4d.0
```
</details>

Create Plugin: Fix react types errors

---

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

Adds a missing forwardslash to the webpack font loader
Fixes https://github.com/grafana/plugin-tools/issues/249
Fixes #

Fix fonts not loaded correctly on generated bundles

---

packages/create-plugin/templates/github/ci/.github/workflows/ci.yml

This PR makes the following adjustments:
1) Build the backend before running E2E tests (to be able to exercise a datasource)
2) Only run E2E tasks if the cypress directory exists
3) Uploads video output of E2E/cypress failures with 5 day retention
4) Bumps go to 1.20
These are just suggestions and how I've modified my plugins to operate (not all have E2E and build times are slower due to spinning up/down docker)
No issue open currently.
I have these changes active in a panel plugin (an unpublished one)
<details>
<br />
```bash
npm install …
```

create-plugin: updates for ci workflow

---

docusaurus/docs/creating-a-plugin.mdx

Now devs can scaffold scene apps we need to update the docs.
Fixes #
@dprokop feel free to push to this if you feel the wording isn't quite right.

Website: Add explanation for scenes app and link

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/test-build.yml
nx.json
package.json
yarn.lock

This PR replaces Lerna with NX for task running. The main incentive here is that local development can benefit from caching to prevent running commands with the same input. Lerna will still be required for versioning and publishing the packages in this repo.
If we're happy to merge this I think we could apply for an [OSS plan for nx cloud](https://nx.app/pricing) and start using the cache in CI.
Fixes #

Tooling: Use NX instead of Lerna for running tasks

---

jest.config.base.js
packages/create-plugin/templates/common/.config/jest.config.js

Changed to inline source maps for jest
Fixes #267

Create Plugin: Fix Code Coverage for JSX files

---

docusaurus/docs/creating-a-plugin.mdx
docusaurus/docs/folder-structure.md
docusaurus/docs/getting-started.mdx
packages/create-plugin/package.json

This is a PR holding a review of 3 plugins docs, focusing on structure, editorial soundness, and conformity to doc team style guidelines.
Note 1: The label type/docs is not available for this repo, but this issue should be tracked in Docs projects.
Note 2: The contents of this repo will be moved as part of doc plan phase 2. However, the editing will take place in the Docusaurus repo where the files now live. 
This fulfills the doc improvement initiative described in the plugins doc plan.
Plugin developers

Docs: Plugin-tools intro material - Doc review chunk 6

---

packages/create-plugin/templates/app/provisioning/plugins/apps.yaml
packages/create-plugin/templates/scenes-app/provisioning/plugins/apps.yaml

Fixes https://github.com/grafana/plugin-tools/issues/234.
Added Grafana provisioning to enable the scaffolded `app` and `scenes-app` plugins by default when they are run with the generated docker-compose file (`npm run server`).  
<details>
<br />
```bash
npm install @grafana/create-plugin@1.6.0-canary.274.89a40e3.0
yarn add @grafana/create-plugin@1.6.0-canary.274.89a40e3.0
```
</details>

Create Plugin: Enable apps by default

---

package.json
packages/create-plugin/src/bin/run.ts
packages/create-plugin/src/utils/utils.os.ts

Adds a check to the bin file that exits early if windows powershell or command prompt is detected when running commands. Tested by running the following code on a windows VM:
```js
import { platform, release } from 'node:os';
console.log(`This platform is ${platform}`);
console.log(`This platform is ${release()}`);
```
*Windows Command Prompt*
```shell
This platform is win32
This platform is 10.0.22621
```
*Windows PowerShell*
```shell
This platform is win32
This platform is 10.0.22621
```
*Windows WSL*
```shell
This platform is linux
This platform is 5.10.16.3-microsoft-standard-WSL2
```
Related #239
<details>
<summary>📦 Published PR as canary version: <code>Canary …

Create Plugin: Introduce OS check

---

packages/create-plugin/src/constants.ts
packages/create-plugin/templates/common/package.json

Bumps "update-able" dependencies to latest backward-compatible versions. This also allows create-plugin scaffolded plugins to work with Node 20 out the box.
Fixes #262
<details>
<br />
```bash
npm install @grafana/create-plugin@1.6.3-canary.279.2969399.0
npm install @grafana/sign-plugin@1.0.2-canary.279.2969399.0
yarn add @grafana/create-plugin@1.6.3-canary.279.2969399.0
yarn add @grafana/sign-plugin@1.0.2-canary.279.2969399.0
```
</details>

Create Plugin: Bump dependencies

---

docusaurus/docs/getting-started.mdx

[Getting Started](https://grafana.github.io/plugin-tools/docs/getting-started) page lists build tools twice, once under the supported OS section - assuming that was an accident (probably an artifact of a merge). 
None as far as I'm aware.
<!--
- Automatically closes linked issue when the Pull Request is merged.
Usage: "Fixes #<issue number>", or "Fixes (paste link of issue)"
->

Docs: Remove duplicate OS section of getting started page

---

packages/create-plugin/templates/common/.config/jest/utils.js

`rxjs` only includes an es module build which causes jest to fail. This PR adds it to the list of known esmodules to make it easier for devs to write tests.
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@1.6.4-canary.289.3fae44c.0
yarn add @grafana/create-plugin@1.6.4-canary.289.3fae44c.0
```
</details>

Create Plugin: Add rxjs and schema to known Jest ES modules

---

package-lock.json
packages/sign-plugin/package.json
packages/sign-plugin/src/utils/manifest.ts
packages/sign-plugin/src/utils/request.ts

Removes axios as a dependency for sign-plugin. Axios is only used to make a single post request and it adds a layer of "black box" that can make situations like https://github.com/grafana/plugin-tools/issues/290 harder to diagnostic.
Fixes #
<details>
<br />
```bash
npm install @grafana/sign-plugin@1.0.3-canary.292.c5013c7.0
yarn add @grafana/sign-plugin@1.0.3-canary.292.c5013c7.0
```
</details>

Chore: Remove axios as a dependency for sign-plugin

---

docusaurus/website/docusaurus.config.js

Adding 
`<meta name="robots" content="noindex, nofollow">`
globally to the github.io/plugin-tools website to prevent indexing until we reshuffle the content and at some point migrate towards the dev portal.
fyi @josmperez

Adding noindex for now until we reshuffle the content

---

.github/workflows/stale.yml

To keep the issues and PRs up to date

Adding stalebot config

---

packages/create-plugin/templates/common/package.json

Fixes a reported issue where running build after running `npm install` or `yarn install` fails o build with error
`panicked at 'base_dir(./src) must be absolute. Please ensure that `jsc.baseUrl` is specified correctly.'`
The error is fixed by pinning the version of @swc/core to a known working version 1.3.75.
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@1.10.1-canary.346.8316a63.0
yarn add @grafana/create-plugin@1.10.1-canary.346.8316a63.0
```
</details>

Fix swc-core version to 1.3.75 to prevent existing bug with baseUrls

---

docusaurus/website/src/css/custom.css

Adds custom css to make links visible inside a doc's article
This is a temporal fix while saga provides the solution to the base css.
This is how they look with this css
Fixes #

Add CSS to make links visible inside page content

---

packages/create-plugin/templates/common/.config/webpack/utils.ts
packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

To be able to check if file on windows was changed while working in WSL we need to implement poll option for webpack
if we detect WSL we add watchOption -> poll to the config
Fixes #353
<details>
<br />
```bash
npm install @grafana/create-plugin@1.11.0-canary.356.0c5b11c.0
yarn add @grafana/create-plugin@1.11.0-canary.356.0c5b11c.0
```
</details>

create-plugin: Enable webpack watchOption -> poll if WSL is detected

---

docusaurus/website/docusaurus.config.base.js

Adding the noIndex by default back until we start redirecting pages from grafana.com/docs

Adding the noindex back until we start redirecting

---

docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-backend-plugin.md
docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-logs-data-source-plugin.md
docusaurus/docs/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins.md
docusaurus/docs/create-a-plugin/extend-a-plugin/enable-annotations.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
docusaurus/docs/shared/plugin-anatomy.md
packages/create-plugin/templates/_partials/distributing-your-plugin.md
packages/create-plugin/templates/app/README.md
packages/create-plugin/templates/datasource/README.md
packages/create-plugin/templates/panel/README.md

- Update link target for plugin.json from Hugo to Docusaurus site in docs.
- Update link target to https://grafana.comdevelopers/plugin-tools/reference-plugin-json for READMEs

Docs: change link target for plugin.json

---

docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-logs-data-source-plugin.md

The "build a logs data source tutorial" was recently revamped and this PR brings the plugin-tools version to match Hugo version. See https://github.com/grafana/grafana/pull/72441 for latest merger. 
Note:
- Draft = true.

Docs: update logs data source tutorial

---

packages/create-plugin/src/bin/run.ts

When create-plugin detects Windows OS we shoe the error, that this OS is not supported. We need to add access to documentation with details
Fixes #347
<details>
<br />
```bash
npm install @grafana/create-plugin@1.11.0-canary.365.32f6dfa.0
yarn add @grafana/create-plugin@1.11.0-canary.365.32f6dfa.0
```
</details>

create-plugin: Add link to documentation about troubleshooting create-plugin on windows 

---

docusaurus/docs/introduction/error-handling.md
docusaurus/docs/metadata.md
docusaurus/docs/migration-guides/angular-react.md
docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
docusaurus/docs/publish-a-plugin/publishing-and-signing-criteria.md

A few topics don't have the same verbage for the doc title (appearing on TOC) and the H1 at the top. This PR fixes mismatches between doc titles and H1s.

Docs: Fix mismatches between doc titles and H1s

---

packages/create-plugin/templates/common/.config/jest/utils.js

This PR updates the jest `transformIgnorePatterns` regex to ensure nested modules are supported.
<details>
<br />
```bash
npm install @grafana/create-plugin@1.12.1-canary.375.26435ce.0
yarn add @grafana/create-plugin@1.12.1-canary.375.26435ce.0
```
</details>

Update transform regex to detect nested modules

---

docusaurus/docs/migration-guides/update-from-grafana-versions/v10.0.x-v10.1.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v6.x-v7.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v8.3.x-8.4.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v8.x-v9.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v9.1.x-v9.2.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v9.3.x-9.4.x.md
docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md

Since we are running behind a reverse proxy in nginx and are actively hiding `index.html` fetches from urls to keep them pretty -> there is no way for nginx to know when to fetch a static asset and when to fetch a `${page}/index.html`
This leads to pages that have dots in url being broken if they have no trailing `/index.html` set. 
To make our lives easier - we should just avoid dots in the url while we are running in reverse proxy mode.

Move to underscore from dots in urls

---

docusaurus/docs/create-a-plugin/develop-a-plugin/error-handling.md
docusaurus/docs/create-a-plugin/extend-a-plugin/error-handling.md

I propose to move the error handling topic out of Introduction into Create a plugin/Develop a plugin. As it contains a mix of conceptual and how-to information, the latter seems more appropriate.

Docs: move error handling topic

---

docusaurus/docs/get-started/get-started.mdx

Docs: fix typo on get-started.mdx

---

docusaurus/docs/introduction/index.md
docusaurus/docs/migration-guides/index.md
docusaurus/docs/tutorials/index.md

Add indexes for Introduction, Tutorials, and Migration Guide sections using the DocCardList Docusaurus shortcode. The purpose of these index is to serve as temporary landing pages while we develop introductory content to help navigate users through this content. Also, they are helpful so that the old Hugo doc content can be migrated to parallel locations in the doc set.

Docs: Add three indexes as temporary landing pages

---

.github/workflows/deploy-to-developer-portal-dev.yml
docusaurus/website/docusaurus.config.base.js

Since we have started redirecting the docs content to developer portal, there is no need for noIndex anymore and we can let the content get into SERPs.
Referenced PR https://github.com/grafana/website/pull/15415

Cleanup commented out workflow code and remove the noindex

---

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

It should solve the following issue: https://github.com/grafana/plugin-tools/issues/229
Tested for the following plugins:
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@1.12.3-canary.427.81fafa5.0
npm install @grafana/sign-plugin@1.1.1-canary.427.81fafa5.0
yarn add @grafana/create-plugin@1.12.3-canary.427.81fafa5.0
yarn add @grafana/sign-plugin@1.1.1-canary.427.81fafa5.0
```
</details>

Bugfix: Enable plugins to lazy load modules

---

.autorc
.github/dependabot.yml

Should theoretically control what labels are set, not sure it practically works but let's see.

Adjusting dependabot dependency labels

---

docusaurus/docs/create-a-plugin/develop-a-plugin/plugin-spellcheck.md

Add internal doc on plugin spellcheck feature.
Per internal Slack conversation, we are keeping this in draft. Moving from grafana repo to plugin-tools repo. Related internal discussion at https://raintank-corp.slack.com/archives/C024NL6AEJH/p1683014954787059?thread_ts=1682980023.733219&cid=C024NL6AEJH

Docs: add plugin spellcheck internal doc

---

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

Webpack runtimes that load chunks dynamically can currently conflict between plugin builds. This PR fixes it by providing `output.uniqueName` set to the plugin id. [More info in webpack docs](https://webpack.js.org/configuration/output/#outputuniquename).
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@2.1.2-canary.464.e8bec90.0
yarn add @grafana/create-plugin@2.1.2-canary.464.e8bec90.0
```
</details>

Create Plugin: Prevent conflicting webpack runtimes

---

docusaurus/docs/get-started/get-started.mdx

The install command on the get started page is missing. This PR fixes that.
| Before | After |
| --- | --- |
| <img width="1004" alt="Screenshot 2023-10-17 at 08 47 44" src="https://github.com/grafana/plugin-tools/assets/73201/04ae3639-d15c-4e44-a005-554e96f88e56"> | <img width="992" alt="Screenshot 2023-10-17 at 08 47 35" src="https://github.com/grafana/plugin-tools/assets/73201/aef90901-d783-44a7-87ac-abbe30283454"> |
Fixes #

Website: Fix install command on get started page

---

docusaurus/docs/migration-guides/angular-react-convert-from-kbn.md

Adds docs for angular to react plugin conversions that use the kbn package.
https://github.com/grafana/grafana/issues/47105

migration-docs: guide for kbn conversion

---

docusaurus/docs/get-started/get-started.mdx
package.json

The link from get-started to backend developer resources appears to randomly break. I believe it's caused by the period at the start of the link.
Fixes #

Docs: fix backend developer resources link

---

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts

:wave:  Having multiple images with same filename but under different folders in `img/` causes webpack to error in dev mode because output path only includes the filename. For example we have `img/technology/generic.svg` and `/img/cloud/generic.svg' and it tries to ouput both into `img/generic.svg`, causing a conflict.
This PR makes dev output filename use the full img path, fixing this issue

Templates/Webpack: Include full path in dev mode image output filename

---

docusaurus/website/src/theme/tracking/index.ts

@josmperez has reported some odd behaviour with docusaurus crashing in dev. Looking at the stack trace it appears the tracking code will error if it cannot find a canonical link on the page. This PR fixes that by checking the link exists before attempting to get the `href` attribute.
Fixes #

Website: Fix tracking issue with missing canonical links

---

docusaurus/docs/tutorials/build-a-logs-data-source-plugin.md

Part of https://github.com/grafana/grafana/pull/77232, where we're deprecating the `showContextToggle` function.
Related to https://github.com/grafana/grafana/issues/66819

Log context support: deprecate showContextToggle

---

packages/create-plugin/fixtures/test-template/src/plugin.json
packages/create-plugin/templates/app/src/plugin.json
packages/create-plugin/templates/datasource/src/plugin.json
packages/create-plugin/templates/panel/src/plugin.json
packages/create-plugin/templates/scenes-app/src/plugin.json

While starting to write a new plugin using the `@grafana/create-plugin` tool, I realized the boilerplate it generates includes a reference to the `master` branch as the source of the schema definition for the `plugin.json` file.
So, I decided to open this PR which updates the `$schema` reference in `plugin.json` templates to replace `master` with `main`, which is the correct one, I think. Otherwise, just feel free to dismiss it.
N/A
N/A

Create Plugin: Replace 'master' with 'main' on  ref

---

docusaurus/docs/tutorials/build-a-logs-data-source-plugin.md

Part of https://github.com/grafana/grafana/issues/77697. Changes recommended log data Frame format based on updated dataPlane format.

Logs: Update labels field based on updates dataPlane spec

---

docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
packages/create-plugin/templates/github/ci/.github/workflows/release.yml

- Updates release workflow to generate a sha1sum file that GCOM can use, docs updated also to not reference non-preferred MD5 option
- Updates go to 1.21
N/A
<details>
<br />
```bash
npm install @grafana/create-plugin@2.5.0-canary.503.d548172.0
yarn add @grafana/create-plugin@2.5.0-canary.503.d548172.0
```
</details>

update to use sha1sum and minor workflow updates

---

docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md

Add new FAQ on toolkit deprecation to https://grafana.com/developers/plugin-tools/publish-a-plugin/publish-a-plugin
Fixes https://github.com/grafana/grafana/issues/68635
Note: Issue 68635 requests adding a note to the "Sign a plugin" page, but I didn't see a specific relevance to signing. Open to suggestions though for a specific note/location.

Docs: Add FAQ on toolkit to publishing section

---

packages/plugin-e2e/package.json
packages/plugin-e2e/src/e2e-selectors/index.ts
packages/plugin-e2e/src/e2e-selectors/resolver.test.ts
packages/plugin-e2e/src/e2e-selectors/resolver.ts
packages/plugin-e2e/src/e2e-selectors/types.ts
packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
packages/plugin-e2e/src/e2e-selectors/versioned/constants.ts
packages/plugin-e2e/src/e2e-selectors/versioned/index.ts
packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
packages/plugin-e2e/src/e2e-selectors/versioned/types.ts
packages/plugin-e2e/src/index.ts

So in the plugin e2e design doc, it was decided that the e2e selectors should live in a separate npm package that is (unlike today) detached from Grafana releases. This however, would be a big undertaking that requires a lot of coordination across many teams. For that reason, it may make sense to keep the selectors within the plugin-e2e package for some time, and then move them to its own package once we know plugin authors are starting to use plugin-e2e.
Most of the code here is copied from @grafana/e2e-selectors, and there's a bunch of things that can (and will!) be improved before plugin-e2e is released publicly the first time. 
* All selector that are not used by plugin-e2e (the ones that don't have a version associated with it) should be …

Plugin E2E: Add E2E selectors

---

.github/workflows/playwright.yml
.gitignore
package-lock.json
packages/plugin-e2e/package.json
packages/plugin-e2e/playwright.config.ts
packages/plugin-e2e/src/api.ts
packages/plugin-e2e/src/fixtures/grafanaVersion.ts
packages/plugin-e2e/src/fixtures/index.ts
packages/plugin-e2e/src/fixtures/selectors.ts
packages/plugin-e2e/src/fixtures/types.ts
packages/plugin-e2e/src/index.ts
packages/plugin-e2e/tests/README.md
packages/plugin-e2e/tests/selectors.spec.ts

This PR adds two new Playwright fixtures for resolving grafana version and selectors (for the given grafana version). Also added a simple playwright e2e test that showcases how these fixtures can be used in practise. There's a simple GH action that will run the tests in two versions of Grafana, just to demonstrate the resolving of selectors work. 
If you want to run tests on your local machine: 
```bash
GRAFANA_VERSION=<version> npm run server --w @grafana/plugin-e2e
#in another terminal
npm run playwright:test --w @grafana/plugin-e2e
```
https://github.com/grafana/grafana/issues/78078
Fixes #
Adding an nvmrc file for this workspace only. Is that a bad idea?

Plugin E2E: Add first fixtures

---

docusaurus/docs/ui-extensions/register-an-extension.md

If/when https://github.com/grafana/grafana/pull/77900 is merged there will be a new extension point which plugin developers can register against. This PR adds the ID of the extension point to the `register-an-extension` docs.

Mention new alerting extension point PR in docs

---

.github/workflows/playwright.yml
packages/plugin-e2e/docker-compose.yaml
packages/plugin-e2e/provisioning/dashboards/dashboards.yaml
packages/plugin-e2e/provisioning/dashboards/google-sheets.json
packages/plugin-e2e/provisioning/dashboards/redshift.json
packages/plugin-e2e/provisioning/datasources/cloudwatch.yaml
packages/plugin-e2e/provisioning/datasources/redshift.yaml

This PR adds a few provisioning files for data sources and dashboards that will be used in E2E tests. Note that secrets are defined for this repo, and if you want this to work on your local machine you can get export env variables. Secrets can be found in the plugin-provisioning repo. 
Fixes #

Plugin E2E: Add provisioning files

---

packages/create-plugin/templates/common/_package.json
packages/create-plugin/templates/scenes-app/src/components/App/App.tsx
packages/create-plugin/templates/scenes-app/src/components/AppConfig/AppConfig.tsx
packages/create-plugin/templates/scenes-app/src/components/Routes/Routes.tsx

Updates the scenes-app library version in the scenes-app template
Fixes using some deprecated methods in the generated code and removing barrel imports
fixes https://github.com/grafana/plugin-tools/issues/570
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@2.9.0-canary.573.1b536d6.0
yarn add @grafana/create-plugin@2.9.0-canary.573.1b536d6.0
```
</details>

Update the scenes-app template to use the latest scenes library and fix some template code style errors
