grafana/plugin-tools

yarn.lock
Result of running `yarn` post merge of #72
=> Chore: Refresh yarn.lock file (removes unused grafana/data)

.github/workflows/npm-bump-version.yml
It also adds `build` as a step to make sure the package is good for publishing
=> Fix npm bump running test

packages/create-plugin/fixtures/test-template/src/plugin.json, packages/create-plugin/src/constants.ts, packages/create-plugin/src/utils/tests/utils.plugin.test.ts, packages/create-plugin/src/utils/utils.files.ts, packages/create-plugin/templates/app/src/plugin.json, packages/create-plugin/templates/datasource/src/plugin.json
Fixes https://github.com/grafana/plugin-tools/issues/90
=> Generate plugin.json backend fields based on user responses

packages/create-plugin/templates/app/src/plugin.json, packages/create-plugin/templates/panel/src/plugin.json
Closes https://github.com/grafana/plugin-tools/issues/92
=> Add missing keywords field to plugin.json

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Follow up to #103 which accidentally ignored css in node_modules which will cause npm packages with css to fail to build.
Fixes #97
=> Fix: Don't ignore node_modules css files

.github/ISSUE_TEMPLATE/config.yml
Follow up to #83 where the introduction of issue templates prevents being able to create empty issues.
Fixes #
=> Chore: remove flag so empty issues can be created

.autorc, .github/workflows/ci.yml, package.json, yarn.lock
Adds the slack plugin to auto so we get automated release messaging in our ci channel.
Example:
Fixes #
=> CI: Introduce slack plugin for automating release messages

.autorc
Sets the [`atTarget`](https://intuit.github.io/auto/docs/generated/slack#attarget) property for the auto slack plugin to prevent from pinging the entire slack channel where there is a new release.
Fixes #
I've created a PR in the auto repo that updates the `atTarget` so we can [disable pinging](https://github.com/intuit/auto/pull/2272). Whilst we wait to see how that pans out I guess we can continue with this approach for now.
=> CI: Silence slack from pinging entire channel

packages/create-plugin/src/constants.ts
This PR updates create-plugin to use the latest version of `@grafana` packages when scaffolding a new plugin.
Fixes #
Given we do a release once a week I'm not sure about how feasible it is to manage the grafana version in this way. Another option is to use the `latest` keyword so a plugin dev will always get the latest version of the packages however I'm a little loathed to do that right now as I worry we won't be able to easily understand if the templates work with the latest version of packages. 🤔 
<details>
<br />
```bash
npm install …
```
=> Create-Plugin: Update grafanaVersion to 9.2.5

.github/workflows/ci.yml, packages/create-plugin/scripts/generate-app-backend.js, packages/create-plugin/templates/backend-app/pkg/main.go, packages/create-plugin/templates/backend/pkg/main.go
This PR addresses the issue where the name passed to the first argument of `datasource.Manage()` and `app.Manage()` in main.go does not match the id in plugin.json.
It also addresses [CI errors post publish](https://github.com/grafana/plugin-tools/actions/runs/3539282544) where the NPM token doesn't exist during clean up by moving the env definition to the `release` job.
Fixes #147
<details>
<br />
```bash
npm install @grafana/create-plugin@0.6.2-canary.159.5d76487.0
yarn add @grafana/create-plugin@0.6.2-canary.159.5d76487.0
```
</details>
=> Create Plugin: Fix Plugin ID in backend to match plugin.json

packages/create-plugin/src/commands/generate.plopfile.ts, packages/create-plugin/templates/_partials/distributing-your-plugin.md, packages/create-plugin/templates/app/README.md, packages/create-plugin/templates/common/package.json, packages/create-plugin/templates/datasource/README.md, packages/create-plugin/templates/github/ci/.github/workflows/ci.yml, packages/create-plugin/templates/github/ci/.github/workflows/release.yml, packages/create-plugin/templates/github/is-compatible/.github/workflows/is-compatible.yml, packages/create-plugin/templates/panel/README.md
The release workflow that is scaffolded by create-plugin has a dependency on toolkit to sign plugins. Now sign-plugin is available we can leverage it instead. This PR does the following:
Fixes #115
<details>
<br />
```bash
npm install @grafana/create-plugin@0.7.0-canary.160.9695113.0
yarn add @grafana/create-plugin@0.7.0-canary.160.9695113.0
```
</details>
=> Create plugin: Introduce sign-plugin

docusaurus/website/static/google33723ad8dc697437.html
Adding a google console search verification file to track site usage / appearance in search results
=> Adding google search console verification file

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/test-build.yml
Removes the need for a personal access token in favour of using the github token and permissions.
I cherry picked these commits from #182 which verifies it's working for publishing to NPM but that PR is held up with potential docs changes.
Fixes #
=> CI: Update workflows to use permissions rather than PAT

docusaurus/docs/folder-structure.md, docusaurus/docs/nested-plugins.md, docusaurus/website/sidebars.js, packages/create-plugin/src/commands/generate.plopfile.ts, packages/create-plugin/templates/common/.config/webpack/utils.ts
Nested plugins are producing dist directory structures that prevent Grafana from loading the plugins.
```
./dist
├── CHANGELOG.md
├── LICENSE
├── README.md
├── datasource
│   ├── img
│   │   └── logo.svg
│   └── plugin.json
├── grafana-create-tool-nested-plugins-error
│   ├── module.js
│   └── module.js.map
├── img
│   └── logo.svg
├── plugin.json
└── src
├── module.js
└── module.js.map
```
```
./dist
├── CHANGELOG.md
├── LICENSE
├── README.md
├── datasource
│   ├── img
│   │   └── logo.svg
│   ├── module.js
│   ├── module.js.map
│   └── plugin.json
├── img
│   └── logo.svg
├── module.js
├── module.js.map
└── plugin.json
```
Fixes #180 
<details>
<summary>📦 Published PR as canary …
=> Create Plugin: Make sure nested plugins dist directory structure is correct

packages/sign-plugin/src/commands/sign.command.ts
Returns a non zero exit code if an error occurs. Useful for CI.
Fixes #186
<details>
<br />
```bash
npm install @grafana/sign-plugin@0.0.3-canary.187.5dd9cd6.0
yarn add @grafana/sign-plugin@0.0.3-canary.187.5dd9cd6.0
```
</details>
=> Sign Plugin: Return non zero exit code if error occurs

packages/create-plugin/templates/_partials/frontend-getting-started.md
**What this PR does / why we need it**: Just some typos fixed in 'packages/create-plugin/templates/_partials/frontend-getting-started.md'
**Which issue(s) this PR fixes**: None
=> Minor typo fixed and improved comment consistency in frontend-getting-started.md

CODE_OF_CONDUCT.md
Adds Code of Conduct to the project; using same as other Grafana projects.
Fixes #
=> docs: adds code of conduct

packages/create-plugin/package.json, packages/create-plugin/src/commands/generate-actions/print-success-message.ts, packages/create-plugin/src/commands/generate-actions/update-go-sdk-and-packages.ts, packages/create-plugin/src/commands/generate.plopfile.ts, packages/create-plugin/src/commands/types.ts, packages/create-plugin/src/utils/utils.path.ts, yarn.lock
We want newly generated plugins to always use the latest grafana go sdk. Currently the version is hardcoded in the generator templates. With this custom action we run `go get [grafana-sdk]` in the generated code upon generation which updates the go sdk to its latest version.
This pr implements the logic to run the update when the enviroment is ready to do so.
Closes https://github.com/grafana/plugin-tools/issues/86
=> Auto update grafana go sdk after generation

.github/ISSUE_TEMPLATE/bug_report.yml
The bug report template [on main](https://github.com/grafana/plugin-tools/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml) appears to be broken. The changes in [this branch](https://github.com/grafana/plugin-tools/blob/jackw/fix-issue-template/.github/ISSUE_TEMPLATE/bug_report.yml) appear to fix it.
=> Fix: GH bug report template

yarn.lock
Applies dependabot patches until we figure out a way for Dependabot to run the workflows without failure.
Fixes #
=> Chore: Apply version bumps

packages/create-plugin/templates/common/src/module.test.ts
https://raintank-corp.slack.com/archives/C024NL6AEJH/p1678796135730009
Fixes #
=> Template: Removed the module.test.ts file from being scafollded by create-plugin

docusaurus/website/package.json, yarn.lock
Keeps Docusaurus and its dependencies up to date.
Fixes #
=> Website: Bump Docusaurus dependencies to 2.4.0

packages/create-plugin/README.md
Related to https://github.com/grafana/plugin-tools/issues/239
Fixes #
=> docs: readme update for windows

packages/create-plugin/README.md
Aligns the readme with the [docs website](https://grafana.github.io/plugin-tools/docs/getting-started?current-package-manager=npm#choosing-a-package-manager).
Fixes #
=> Create Plugin: Update readme for supported package managers

docusaurus/docs/getting-started.mdx
Adds a section to the docs site that lists which operating systems create plugin supports
Related #239
=> Docs: Add supported operating system section

packages/create-plugin/scripts/generate-app-backend.js, packages/create-plugin/scripts/generate-app.js, packages/create-plugin/scripts/generate-datasource-with-backend.js, packages/create-plugin/scripts/generate-datasource-without-backend.js, packages/create-plugin/scripts/generate-panel.js, packages/create-plugin/scripts/generate-scenes-app.js
Currently the errors inside the plop generator are "swallowed", we are not seeing them in the console (which caused us some headaches while trying to add the new app-scenes template).
This PR is fixing this by logging the generator errors to the console.
=> Scripts: Add error-handling to generator scripts

.github/workflows/ci.yml, .github/workflows/deploy.yml
This PR replaces the usage of the GH bot token with a GH app token in workflows which I believe is the preferred way to auth these days.
Fixes #222
I'm not sure how to test this fully other than merge and wait for releases to succeed/break. 😬
=> CI: Use a GH app token

docusaurus/docs/advanced-configuration.md, docusaurus/docs/migrating-from-toolkit.mdx, docusaurus/docs/updating-to-new-releases.mdx
This PR holds a review of plugins docs, focusing on structure, editorial soundness, and conformity to doc team style guidelines.
This fulfills the doc improvement initiative described in the plugins doc plan.
Plugin developers
=> Docs: Plugin-tools - Config and migration - chunk 7

docusaurus/docs/backend.md, docusaurus/docs/ci.md, docusaurus/docs/docker.mdx, docusaurus/docs/frontend.mdx, docusaurus/docs/getting-started.mdx, docusaurus/docs/nested-plugins.mdx
This is a PR holding a review of several plugins docs, focusing on structure, editorial soundness, and conformity to doc team style guidelines.
This fulfills the doc improvement initiative described in the plugins doc plan.
Plugin developers
=> Docs: Plugin-tools development material - chunk 8

.github/workflows/deploy.yml, .github/workflows/test-build.yml
Moved the repo to NPM and neglected to update the deploy gh workflow.
Fixes #
=> CI: Fix website deploy script

docusaurus/website/docusaurus.config.js
The docs in Grafana got moved around causing docusaurus to break locally. Updates also caused regexs to fail. This PR addresses both of these things...
Fixes #
=> Website: Update Docusaurus config post Grafana docs update

docusaurus/website/README.md, packages/create-plugin/CONTRIBUTING.md, packages/sign-plugin/CONTRIBUTING.md
We moved from yarn to npm for this repo and neglected to update some of the commands in the various markdown files.
Fixes #
=> Docs: Update readme and contributing to use NPM

packages/create-plugin/templates/common/src/README.md
Developers contributing plugins often ask for advice on how they can best advertise their plugin to users and what sort of content to include in a README, which in effect becomes the front page for the plugin in the catalog. This PR introduces guidance in the form of comments in the generated README. 
Fixes #
Note - there may be an issue that Grafana.com displays HTML comments. We may want to hold off on this enhancement until investigating further and either fixing or introducing new validation.
=> Create Plugin: add readme best practice example

packages/create-plugin/templates/common/package.json, packages/create-plugin/templates/scenes-app/src/pages/HelloWorld/helloWorldScene.tsx, packages/create-plugin/templates/scenes-app/src/pages/Home/scenes.tsx, packages/create-plugin/templates/scenes-app/src/pages/WithDrilldown/panels.tsx, packages/create-plugin/templates/scenes-app/src/pages/WithDrilldown/scenes.tsx
This updates scenes template to use latest API.
<details>
<br />
```bash
npm install @grafana/create-plugin@1.6.4-canary.287.cbc2025.0
yarn add @grafana/create-plugin@1.6.4-canary.287.cbc2025.0
```
</details>
=> Create Plugin: Update scenes to latest version

docusaurus/website/docusaurus.config.js
Adds an alias to docsusaurus to make it easier to embed shared docs in other pages. Once merged docs writers can add shared markdown content to `docusaurus/docs/shared` and then include it in any page like so:
```
import SharedContent from '@shared/path/to/shared/content.md';
<SharedContent />
```
Fixes #
=> Website: Add shared alias for includes

docusaurus/website/docusaurus.config.js, docusaurus/website/package.json, docusaurus/website/src/css/custom.css, package-lock.json
Adds a remark plugin to transform markdown image syntax into figures with captions.
Works with standard markdown image syntax. e.g.
```
```
Fixes #
=> Website: Introduce captions for images

LICENSE
Copies existing license file and adds to top level so that our repo isnt flagged as lacking a license file by scanning tools and humans can easily see when browsing.
Fixes #
=> (chore): add top level license file

docusaurus/website/docusaurus.config.devportal.js
Previous re-theme PR has broken the builds for dev portal. This PR aims to address this by fixing the [broken footer links](https://github.com/grafana/plugin-tools/actions/runs/5807068372/job/15741216617).
Fixes #
=> Website: Fix footer links for dev portal

.github/workflows/test-build.yml, docusaurus/docs/get-started/get-started.mdx, docusaurus/website/docusaurus.config.devportal.js, package.json
Another attempt at fixing the dev portal deploy.
Fixes #
=> Website: fix link and config for dev portal deploy

.github/workflows/deploy-to-developer-portal-dev.yml, .github/workflows/deploy-to-developer-portal.yml, docusaurus/website/docusaurus.config.devportal.js
Switching to the _real_ dev gcs bucket and switching dev deployment to manual triggers
=> Switching to dev bucket and manual dev workflow triggers

docusaurus/docs/introduction/grafana-plugin-sdk-for-go.md
=> docs: fix missing link

.github/workflows/deploy-to-developer-portal-prod.yml, docusaurus/website/docusaurus.config.devportal.prod.js
Deployment for production bucket for plugin tools sub-site.
=> prod deployment

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Changes the repository configuration to allow feature requests as issues (with template) - in line with proposed changes to Grafana core.
Provides a link to the community for general Q&A
Fixes #
Haven't tested this...
=> (chore): change FR to issue

docusaurus/docs/create-a-plugin/backend.md
Fix link to SDK from backend.md.
=> Docs: Fix link in backend topic

docusaurus/docs/metadata.md
Add plugin.json file. Bring over file as it exists today on developers/plugins site.
Note:
- Discuss the process (manual, automated, etc.) for updating this file.
=> Docs: add metadata (plugin.json) reference

docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-backend-plugin.md, docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-plugin.md, docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-logs-data-source-plugin.md, docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin-with-d3.md, docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin.md, docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-streaming-data-source-plugin.md
=> quick fix for drafts

docusaurus/docs/get-started/get-started.mdx, docusaurus/website/docusaurus.config.base.js, docusaurus/website/docusaurus.config.dev.js, docusaurus/website/docusaurus.config.js, docusaurus/website/src/css/custom.css
- Fixes links in docs so they are using the same text-link colour (blue) across the site without impacting links in specific components inside markdown (e.g. alerts).
- Adds a `portal home` link to the header and footer. (Replaces the docs link in the header which felt a bit redundant given the sidebar is always there.)
- Removes confusing underscores from the answers in get-started which were being rendered in the html.
Fixes #
=> Docs: Add portal home links

docusaurus/website/README.md, docusaurus/website/docusaurus.config.base.js, docusaurus/website/package.json, docusaurus/website/src/css/custom.css, package-lock.json
Introduces a local search to the plugin-tools site. 
https://github.com/grafana/plugin-tools/assets/73201/0fb3590c-5f9b-40a9-8768-cd15f5f66ab5
Related https://github.com/grafana/grafana-developer-portal/issues/9
=> Website: Introduce Search 

docusaurus/docs/ui-extensions/_category_.json
Changed so UI extensions section is not collapsed by default.
Fixes #
=> Changed so UI extensions section isnt collapsed by default

docusaurus/docs/get-started/get-started.mdx
=> docs: remove scenes public preview caveat

docusaurus/docs/get-started/get-started.mdx
=> docs: update pre-reqs

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
CodeClimate picks up three lint issues in the generated webpack config, two missing semicolons and spacing in an if statement.
None
=> webpack template: minor lint fixes

docusaurus/docs/troubleshooting.md
=> docs: add docker advice

packages/create-plugin/templates/common/.config/webpack/webpack.config.ts, packages/create-plugin/templates/common/package.json
See my comment here: https://github.com/grafana/plugin-tools/issues/344#issuecomment-1738957634
Relates to #344 
=> Create-plugin: Make baseURL absolute and bump swc/core

.github/workflows/issue_commands.json, .github/workflows/typedocs.yml
Add workflows for tech docs process -- see https://github.com/grafana/technical-documentation/wiki/Project-management#about-the-typedocs-label-workflow for details
=> Docs: Add workflows for tech docs

packages/create-plugin/src/commands/update.command.ts, packages/create-plugin/src/utils/tests/utils.npm.test.ts, packages/create-plugin/src/utils/utils.npm.ts, packages/create-plugin/src/utils/utils.packageManager.ts, packages/create-plugin/src/utils/utils.packagejson.ts
It makes sure that only dev dependencies are updated when the update command runs. This avoids problems with conflicting versions of dependencies between grafana versions
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@2.1.0-canary.458.bd6cbd0.0
yarn add @grafana/create-plugin@2.1.0-canary.458.bd6cbd0.0
```
</details>
=> Update only dev dependencies when the update command runs

packages/create-plugin/templates/_partials/backend-getting-started.md, packages/create-plugin/templates/_partials/distributing-your-plugin.md, packages/create-plugin/templates/app/README.md, packages/create-plugin/templates/backend/pkg/plugin/datasource.go, packages/create-plugin/templates/common/src/README.md, packages/create-plugin/templates/datasource/README.md, packages/create-plugin/templates/github/ci/.github/workflows/release.yml, packages/create-plugin/templates/panel/README.md, packages/sign-plugin/README.md, packages/sign-plugin/src/utils/manifest.ts
Fix broken links in package files.
=> Docs: Fix broken links in package files

docusaurus/docs/create-a-plugin/develop-a-plugin/plugin-spellcheck.md
Minor fix to metadata in spellcheck (Internal file).
=> Fix metadata in spellcheck file

docusaurus/docs/introduction/plugin-types-usage.md
=> fix plugin-types-usage.md

packages/create-plugin/src/utils/utils.packagejson.ts
A previous PR renamed the package.json template file to _package.json to solve issues with tooling automatically trying to read configs from any package.json it finds relative to the changed file. This broke upgrade/migrate as create-plugin could no longer find the package.json template.
Fixes #485 
<details>
<br />
```bash
npm install @grafana/create-plugin@2.2.2-canary.487.2293030.0
yarn add @grafana/create-plugin@2.2.2-canary.487.2293030.0
```
</details>
=> Create Plugin: Fix migrate and update commands

docusaurus/website/src/css/custom.css
Updates the styles for admonitions / alerts so links are more visible.
Fixes #482
=> Website: Update theme for alert

docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-frontend.mdx, docusaurus/docs/create-a-plugin/extend-a-plugin/extend-configurations.md, packages/create-plugin/templates/common/.config/_eslintrc, packages/create-plugin/templates/common/.config/tsconfig.json, packages/create-plugin/templates/common/_package.json
Adds an eslint deprecation plugin so plugin developers spot deprecations as they upgrade their `@grafana` dependencies.
Here's an example of what the lint task will print out for deprecations.
```shell
yarn lint
yarn run v1.22.19
$ eslint --cache --ignore-path ./.gitignore --ext .js,.jsx,.ts,.tsx .
/Users/jackwestbrook/dev/grafana/plugin-tools/packages/create-plugin/generated/src/components/AppConfig/AppConfig.tsx
104:27  warning  'GrafanaTheme' is deprecated. use GrafanaTheme2                    deprecation/deprecation
126:42  warning  'datasourceRequest' is deprecated. Use the fetch function instead  deprecation/deprecation
✖ 2 problems (0 errors, 2 warnings)
✨  Done in 6.13s.
```
**Note**: It's worth pointing out that whilst this change brings …
=> Create Plugin: Lint Deprecation Warnings

docusaurus/docs/get-started/set-up-development-environment.mdx, docusaurus/docs/introduction/manage-npm-dependencies.md
[Puts back the admonition](https://github.com/grafana/plugin-tools/pull/472#discussion_r1366766664) explaining that the dev env also uses the dynamic linking to avoid confusion. Also fixes missing words in dev env doc admonition.
Fixes #
=> Website: Add dev env alert to npm deps doc

docusaurus/docs/get-started/set-up-development-environment.mdx
Remove duplicated text 
Fixes #
=> Remove duplicated text from dev env doc

docusaurus/docs/introduction/backend.md
Remove extraneous paragraph. Re [internal bug report](https://raintank-corp.slack.com/archives/C024NL6AEJH/p1698348527906839?thread_ts=1698341735.340909&cid=C024NL6AEJH).
=> Docs: Fix error in backend plugins doc in caching section

docusaurus/website/src/components/DocLinkList/DocLinkList.tsx, docusaurus/website/src/components/DocLinkList/styles.module.css, docusaurus/website/src/theme/MDXComponents.tsx
Minimises the space taken up by "index" pages and prevents truncation of descriptions.
Related #473
=> Website: Add a DocLinkList component

packages/create-plugin/templates/backend-app/pkg/plugin/resources_test.go
Scaffolding an app with backend creates broken test due to missing params.
```
not enough arguments in call to NewApp
have (backend.AppInstanceSettings)
want (context.Context, backend.AppInstanceSettings)
```
Fixes #
<details>
<br />
```bash
npm install @grafana/create-plugin@2.4.1-canary.518.401bff6.0
yarn add @grafana/create-plugin@2.4.1-canary.518.401bff6.0
```
</details>
=> Create Plugin: Fix app backend test

docusaurus/docs/introduction/plugin-lifecycle.md
Makes it easier to discover and reference in links
Fixes #
=> docs: move troubleshooting plugin loading

CONTRIBUTING.md, README.md, docusaurus/website/CONTRIBUTING.md, packages/create-plugin/CONTRIBUTING.md, packages/sign-plugin/CONTRIBUTING.md
Changes to tooling or processes haven't been reflected in the contributing guidelines as there are still mentions of yarn and no explanation of how to run nx commands or basic info on how to contribute to the docs website.
Fixes #
=> Docs: Update contribution guides

CONTRIBUTING.md, README.md, docusaurus/website/CONTRIBUTING.md, packages/sign-plugin/CONTRIBUTING.md
Follow up PR to #534 . This PR addresses the following things:
- Fixes whitespace issues with additional resources list in README
- Removes duplicate "Below are the main commands used for developing sign-plugin." from sign-plugin Contributing.md
- Adds info related to website deployments (Dev and Prod) to website Contributing.md
- Highlights we should have issues before code contributions are made.
- Removes mentions of labels that don't exist.
Fixes #
=> Docs: Further updates to contributing guides

docusaurus/docs/create-a-plugin/develop-a-plugin/plugin-spellcheck.md, docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-data-frames.md, docusaurus/docs/create-a-plugin/extend-a-plugin/add-anonymous-usage-reporting.md, docusaurus/docs/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins.md, docusaurus/docs/create-a-plugin/extend-a-plugin/add-query-editor-help.md, docusaurus/docs/create-a-plugin/extend-a-plugin/add-support-for-explore-queries.md, docusaurus/docs/create-a-plugin/extend-a-plugin/add-support-for-variables.md, docusaurus/docs/create-a-plugin/extend-a-plugin/custom-panel-option-editors.md, docusaurus/docs/create-a-plugin/extend-a-plugin/enable-annotations.md, docusaurus/docs/create-a-plugin/extend-a-plugin/extend-configurations.md, docusaurus/docs/get-started/get-started.mdx, docusaurus/docs/get-started/prompts-cli.md, docusaurus/docs/get-started/set-up-development-environment.mdx, docusaurus/docs/migration-guides/angular-react/angular-react.md, docusaurus/docs/publish-a-plugin/package-a-plugin.md, docusaurus/docs/shared/create-plugin-backend.md, docusaurus/docs/shared/create-plugin-frontend.md, docusaurus/docs/shared/plugin-anatomy.md, docusaurus/docs/snippets/createplugin-build-ci.npm.md, docusaurus/docs/snippets/createplugin-build-ci.pnpm.md, docusaurus/docs/snippets/createplugin-build-ci.yarn.md, docusaurus/docs/tutorials/build-a-data-source-backend-plugin.md, docusaurus/docs/tutorials/build-a-data-source-plugin.md, docusaurus/docs/tutorials/build-a-logs-data-source-plugin.md, docusaurus/docs/tutorials/build-a-panel-plugin-with-d3.md, docusaurus/docs/tutorials/build-a-panel-plugin.md, docusaurus/docs/tutorials/build-a-streaming-data-source-plugin.md, docusaurus/docs/ui-extensions/create-an-extension-point.md, docusaurus/docs/ui-extensions/register-an-extension.md
This PR fixes issues where code blocks or admonitions indentation breaks list numbering and layout. Also makes use of tsx code language where necessary, adds title for code blocks and replaces yarn commands with npm commands.
Fixes #
=> Docs: Fix code block indentations and use titles and tsx

docusaurus/docs/create-a-plugin/extend-a-plugin/add-anonymous-usage-reporting.md
Clarify second code example on page. 
Fixes: https://github.com/grafana/grafana/issues/67874
=> Add code comments on 'Add anonymous usage reporting' topic

.github/workflows/typedocs.yml
Skips triggering issue commands action that reacts to labels for dependabot PRs
=> should avoid running for dependabot prs
